<?php


namespace Genl\Matice\Commands;


use Genl\Matice\Facades\Matice;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class TranslationsGeneratorCommand extends Command
{
    protected $signature = 'matice:generate'; // {path=./resources/assets/js/matice_translations.js}

    protected $description = 'Generate js file for including in build process';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * handle function
     */
    public function handle()
    {
        $path = config('matice.generate_translations_path'); // $this->argument('path');
        $generatedTranslations = Matice::generate(null, false, false);
        $generatedTranslations = ('/*
|--------------------------------------------------------------------------
| Generated Laravel translations
|--------------------------------------------------------------------------
|
| This file is autogenerated and should not be modified.
| To load new translations run: php artisan matice:generate
|
*/
' . $generatedTranslations .
'
'
        );
        $this->makeDirectory($path);
        File::put($path, $generatedTranslations);
        $this->info("Matice translations file generated at $path");
    }

    protected function makeDirectory(string $path)
    {
        if (! File::isDirectory(dirname($path))) {
            File::makeDirectory(dirname($path), 0777, true, true);
        }
    }
}
